language: java

jdk:
  # optional,you can choose one or more JDKs.
  # To test against multiple JDKs, use the jdk: key in .travis.yml.
  - oraclejdk7
  - openjdk7
  - openjdk6
  
branches:
  excludes:
    - gh-pages

notifications:
  email: false  
  
before_install:
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
  - tar -zxf android-sdk_r21.0.1-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  9 = 2.3.3 or API level 10
  - android update sdk --filter platform-tools,android-16 --no-ui --force > /dev/null
  
script: echo Finish
